"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Detail = { lead: Record<string, string | boolean | null>; purchases: Array<{ purchaseId: string; clientId: string; pricePaid: number; purchasedAt: string; status: string }> };
export default function AdminLeadDetail({ params }: { params: { id: string } }) {
  const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/admin/leads/${encodeURIComponent(params.id)}`, { cache: "no-store" }).then(async r => { if (r.status === 401) { location.href = "/admin/login"; return; } const d = await r.json(); if (!r.ok) throw new Error(d.message); setData(d); }).catch(e => setError(e.message)); }, [params.id]);
  if (error) return <main className="p-8 text-rose-200">{error}</main>; if (!data) return <main className="p-8">Loading lead…</main>;
  const l = data.lead; const fullName = `${l.firstName ?? ""} ${l.lastName ?? ""}`;
  return <main className="mx-auto max-w-6xl p-6 py-8 text-[var(--text-primary)]"><Link href="/admin/leads" className="text-teal-cathedral">← All leads</Link><header className="mt-5 flex flex-wrap justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-teal-cathedral">{data.purchases.length ? "Purchased" : "New"} · {String(l.leadId)}</p><h1 className="text-3xl">{fullName}</h1><p className="text-[var(--text-muted)]">{String(l.state)} · {String(l.coverageInterest)}</p></div><div className="flex flex-wrap gap-2"><button className="rounded border border-teal-cathedral/30 px-3 py-2">Mark reviewed</button><button className="rounded border border-teal-cathedral/30 px-3 py-2">Make available</button><button className="rounded border border-rose-400/30 px-3 py-2 text-rose-200">Do not contact</button></div></header><div className="mt-7 grid gap-5 md:grid-cols-2"><Card title="Contact"><Row k="Email" v={l.email}/><Row k="Phone" v={l.phone}/><Row k="DOB" v={l.dateOfBirth}/><Row k="State" v={l.state}/></Card><Card title="Request"><Row k="Coverage interest" v={l.coverageInterest}/><Row k="Readiness" v={l.purchaseIntent}/><Row k="Life chapter" v={l.veteranStatus}/><Row k="Submitted" v={l.createdAt}/></Card><Card title="Source & campaign"><Row k="Source" v={l.utmSource}/><Row k="Medium" v={l.utmMedium}/><Row k="Campaign" v={l.utmCampaign}/><Row k="Page" v={l.consentPageUrl}/></Card><Card title="Compliance proof"><Row k="TCPA consent" v={l.consentTcpa ? "Recorded" : "Missing"}/><Row k="Privacy consent" v={l.consentPrivacy ? "Recorded" : "Missing"}/><Row k="Timestamp" v={l.consentTimestamp}/><Row k="IP" v={l.consentIp}/><Row k="User agent" v={l.consentUserAgent}/><p className="mt-3 whitespace-pre-wrap rounded bg-black/20 p-3 text-xs">{String(l.consentText || "No snapshot stored")}</p></Card><Card title="Purchase history">{data.purchases.length ? data.purchases.map(p => <p key={p.purchaseId} className="border-b border-white/10 py-2 text-sm">{p.clientId} · ${(p.pricePaid / 100).toFixed(2)} · {p.status} · {new Date(p.purchasedAt).toLocaleString()}</p>) : <p className="text-sm text-[var(--text-muted)]">Not sold or assigned.</p>}</Card><Card title="Activity & internal notes"><p className="text-sm text-[var(--text-muted)]">Submission and purchase events are shown from existing records. Operational status, notes, assignments, and follow-up fields are not yet present in the database.</p><button className="mt-4 rounded border border-teal-cathedral/30 px-3 py-2">Add internal note</button></Card></div></main>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-teal-cathedral/10 bg-black/10 p-5"><h2 className="mb-4 text-lg text-teal-cathedral">{title}</h2>{children}</section> }
function Row({ k, v }: { k: string; v: unknown }) { return <div className="mb-2 grid grid-cols-[9rem_1fr] gap-2 text-sm"><span className="text-[var(--text-muted)]">{k}</span><span className="break-all">{v ? String(v) : "—"}</span></div> }
