'use strict';

/**
 * Codex Ingest — drains the lexicon-proposals queue into the periodic table.
 *
 * Reads .remembrance/lexicon-proposals.json, filters kind='element' +
 * status='active', and generates src/atomic/periodic-table-additions.js with
 * registerElement({ name, atomicProperties, source }) calls.
 *
 * The GHA workflow commits the change on a branch and opens a PR. No more
 * stale queue that nobody consumes. Auto-merge rule (from sweep) picks it up
 * when the additions file changes ≤ 1 file with all checks green.
 */

const fs = require('fs');
const path = require('path');
const { getActiveElements } = require('./lexicon-integrator');

const ADDITIONS_FILE = path.join(process.cwd(), 'src', 'atomic', 'periodic-table-additions.js');

function renderElement(el) {
  const p = el.atomicProperties || {};
  const props = Object.entries(p).map(([k, v]) => {
    if (typeof v === 'string') return `  ${k}: '${v}'`;
    if (typeof v === 'number') return `  ${k}: ${v}`;
    return `  ${k}: ${JSON.stringify(v)}`;
  }).join(',\n');
  return `registerElement({\n  name: '${el.name}',\n  source: '${el.source}',\n  approvedAt: '${el.approvedAt || ''}',\n${props ? props + ',\n' : ''}});`;
}

function renderFile(elements) {
  const header = `'use strict';\n\n// AUTO-GENERATED by codex-ingest. Do not edit by hand.\n// Source: .remembrance/lexicon-proposals.json (kind=element, status=active)\n// Generated: ${new Date().toISOString()}\n// Element count: ${elements.length}\n\nconst { registerElement } = require('./periodic-table');\n\n`;
  if (elements.length === 0) {
    return header + '// No active element proposals to ingest.\n\nmodule.exports = { ingested: 0, generatedAt: new Date().toISOString() };\n';
  }
  return header + elements.map(renderElement).join('\n\n') + `\n\nmodule.exports = { ingested: ${elements.length}, generatedAt: new Date().toISOString() };\n`;
}
renderFile.atomicProperties = {
  charge: 0, valence: 1, mass: 'light', spin: 'even', phase: 'solid',
  reactivity: 'inert', electronegativity: 0.3, group: 3, period: 3,
  harmPotential: 'none', alignment: 'neutral', intention: 'neutral',
  domain: 'covenant',
};

function runIngest(opts = {}) {
  const elements = getActiveElements();
  const seen = new Set();
  const unique = [];
  for (const e of elements) {
    const key = `${e.name}:${e.source}`;
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(e);
  }
  const content = renderFile(unique);
  const dir = path.dirname(ADDITIONS_FILE);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  let prior = null;
  if (fs.existsSync(ADDITIONS_FILE)) prior = fs.readFileSync(ADDITIONS_FILE, 'utf-8');
  if (prior === content) return { changed: false, reason: 'no new elements', count: unique.length };
  if (!opts.dryRun) fs.writeFileSync(ADDITIONS_FILE, content);
  return { changed: true, count: unique.length, file: ADDITIONS_FILE };
}
runIngest.atomicProperties = {
  charge: 1, valence: 3, mass: 'medium', spin: 'odd', phase: 'solid',
  reactivity: 'stable', electronegativity: 0.8, group: 13, period: 6,
  harmPotential: 'none', alignment: 'healing', intention: 'benevolent',
  domain: 'covenant',
};

if (require.main === module) {
  const result = runIngest();
  console.log(JSON.stringify(result, null, 2));
  process.exit(0);
}

module.exports = { runIngest, renderFile, renderElement, ADDITIONS_FILE };
